CREATE TABLE `bank_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`bank_name` varchar(200),
	`account_number` varchar(50),
	`routing_number` varchar(20),
	`type` enum('checking','savings','credit_card','loan','investment') DEFAULT 'checking',
	`currency` varchar(10) DEFAULT 'USD',
	`current_balance` decimal(15,2) DEFAULT '0.00',
	`last_reconciled_at` bigint,
	`account_id` int,
	`is_active` boolean DEFAULT true,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `bank_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bank_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`bank_account_id` int NOT NULL,
	`date` bigint NOT NULL,
	`description` varchar(500),
	`amount` decimal(15,2) NOT NULL,
	`type` enum('debit','credit') NOT NULL,
	`status` enum('unmatched','matched','reconciled','excluded') DEFAULT 'unmatched',
	`matched_journal_entry_id` int,
	`matched_invoice_id` int,
	`matched_bill_id` int,
	`reference` varchar(100),
	`created_at` bigint NOT NULL,
	CONSTRAINT `bank_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `bills` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`bill_number` varchar(50),
	`vendor_id` int,
	`vendor_name` varchar(200),
	`vendor_email` varchar(320),
	`issue_date` bigint NOT NULL,
	`due_date` bigint NOT NULL,
	`status` enum('draft','received','approved','partial','paid','overdue','voided') DEFAULT 'draft',
	`subtotal` decimal(15,2) DEFAULT '0.00',
	`tax_amount` decimal(15,2) DEFAULT '0.00',
	`total` decimal(15,2) DEFAULT '0.00',
	`amount_paid` decimal(15,2) DEFAULT '0.00',
	`currency` varchar(10) DEFAULT 'USD',
	`notes` text,
	`receipt_url` varchar(500),
	`paid_at` bigint,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `bills_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broadcast_campaigns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`type` enum('sms','whatsapp','voice','email') NOT NULL DEFAULT 'sms',
	`message` text,
	`voice_script` text,
	`from_number` varchar(30),
	`messaging_profile_id` varchar(100),
	`status` enum('draft','scheduled','running','completed','paused','failed') DEFAULT 'draft',
	`total_contacts` int DEFAULT 0,
	`sent` int DEFAULT 0,
	`delivered` int DEFAULT 0,
	`failed` int DEFAULT 0,
	`scheduled_at` bigint,
	`started_at` bigint,
	`completed_at` bigint,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `broadcast_campaigns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `broadcast_recipients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`campaign_id` int NOT NULL,
	`user_id` int NOT NULL,
	`name` varchar(200),
	`phone` varchar(30),
	`email` varchar(320),
	`status` enum('pending','sent','delivered','failed','opted_out') DEFAULT 'pending',
	`error_message` varchar(500),
	`sent_at` bigint,
	`created_at` bigint NOT NULL,
	CONSTRAINT `broadcast_recipients_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `chart_of_accounts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`account_number` varchar(20) NOT NULL,
	`name` varchar(200) NOT NULL,
	`type` enum('asset','liability','equity','revenue','expense') NOT NULL,
	`subtype` varchar(100),
	`description` text,
	`is_active` boolean DEFAULT true,
	`parent_id` int,
	`balance` decimal(15,2) DEFAULT '0.00',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `chart_of_accounts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_businesses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`industry` varchar(100) NOT NULL,
	`industry_category` enum('home_services','automotive','medical_wellness','professional_specialty') NOT NULL DEFAULT 'home_services',
	`phone` varchar(30),
	`email` varchar(320),
	`address` text,
	`city` varchar(100),
	`state` varchar(50),
	`zip` varchar(20),
	`country` varchar(10) DEFAULT 'US',
	`logo_url` varchar(512),
	`license_number` varchar(100),
	`insurance_verified` boolean DEFAULT false,
	`google_place_id` varchar(200),
	`average_rating` decimal(3,2) DEFAULT '0.00',
	`total_reviews` int DEFAULT 0,
	`is_active` boolean DEFAULT true,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_businesses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_coaching_notes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`technician_id` int NOT NULL,
	`business_id` int NOT NULL,
	`coaching_type` enum('upsell_missed','pricing_feedback','customer_service','technical_accuracy','on_time_feedback','estimate_conversion','referral_missed','positive_reinforcement') NOT NULL,
	`summary` text NOT NULL,
	`detailed_feedback` text,
	`action_items` json,
	`estimated_revenue_impact` decimal(10,2),
	`technician_acknowledged` boolean DEFAULT false,
	`acknowledged_at` bigint,
	`created_at` bigint NOT NULL,
	CONSTRAINT `fsm_coaching_notes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_customer_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`diagnosis_id` int,
	`estimate_id` int,
	`customer_id` int NOT NULL,
	`business_id` int NOT NULL,
	`diagnosis_summary` text,
	`price_benchmark_summary` text,
	`urgency_rating` enum('fix_now','fix_soon','monitor','optional'),
	`urgency_explanation` text,
	`recommended_next_steps` json,
	`related_services_recommended` json,
	`technician_rating` decimal(3,2),
	`technician_jobs_completed` int,
	`business_rating` decimal(3,2),
	`business_license_verified` boolean DEFAULT false,
	`report_url` varchar(512),
	`report_key` varchar(64),
	`sent_via_sms` boolean DEFAULT false,
	`sent_via_email` boolean DEFAULT false,
	`viewed_at` bigint,
	`second_opinion_requested` boolean DEFAULT false,
	`customer_rating` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_customer_reports_id` PRIMARY KEY(`id`),
	CONSTRAINT `fsm_customer_reports_report_key_unique` UNIQUE(`report_key`)
);
--> statement-breakpoint
CREATE TABLE `fsm_customers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`first_name` varchar(100) NOT NULL,
	`last_name` varchar(100),
	`email` varchar(320),
	`phone` varchar(30),
	`address` text,
	`city` varchar(100),
	`state` varchar(50),
	`zip` varchar(20),
	`notes` text,
	`tags` json,
	`churn_risk` decimal(3,2) DEFAULT '0.00',
	`membership_score` decimal(3,2) DEFAULT '0.00',
	`lifetime_value` decimal(10,2) DEFAULT '0.00',
	`total_jobs` int DEFAULT 0,
	`has_membership` boolean DEFAULT false,
	`membership_expires_at` bigint,
	`referred_by_partner_id` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_customers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_diagnoses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`technician_id` int,
	`symptom_description` text NOT NULL,
	`observation_notes` text,
	`photo_urls` json,
	`video_urls` json,
	`ai_diagnosis` text,
	`ai_confidence_score` int,
	`repair_urgency` enum('fix_now','fix_soon','monitor','optional','second_opinion_advised'),
	`repair_necessity_verdict` text,
	`alternative_options` json,
	`estimated_lifespan` varchar(100),
	`risk_if_unaddressed` text,
	`upsell_opportunities` json,
	`referral_opportunities` json,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_diagnoses_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`customer_id` int NOT NULL,
	`business_id` int NOT NULL,
	`type` varchar(100) NOT NULL,
	`brand` varchar(100),
	`model` varchar(200),
	`serial_number` varchar(100),
	`install_date` bigint,
	`warranty_expiry` bigint,
	`last_service_date` bigint,
	`next_service_due` bigint,
	`condition` enum('excellent','good','fair','poor','critical') DEFAULT 'good',
	`notes` text,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_equipment_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_estimate_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`estimate_id` int NOT NULL,
	`type` enum('labor','part','material','service_fee','disposal') DEFAULT 'labor',
	`description` varchar(500) NOT NULL,
	`quantity` decimal(10,2) DEFAULT '1.00',
	`unit_price` decimal(10,2) NOT NULL,
	`amount` decimal(10,2) NOT NULL,
	`part_number` varchar(100),
	`sort_order` int DEFAULT 0,
	`created_at` bigint NOT NULL,
	CONSTRAINT `fsm_estimate_line_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_estimates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`business_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`technician_id` int,
	`estimate_number` varchar(50) NOT NULL,
	`status` enum('draft','presented','accepted','declined','expired') DEFAULT 'draft',
	`tier` enum('good','better','best') DEFAULT 'better',
	`ai_generated_at` bigint,
	`ai_confidence_score` int,
	`market_price_low` decimal(10,2),
	`market_price_high` decimal(10,2),
	`market_price_avg` decimal(10,2),
	`price_position` enum('below_market','at_market','above_market'),
	`ai_pricing_notes` text,
	`subtotal` decimal(10,2) DEFAULT '0.00',
	`tax_rate` decimal(5,2) DEFAULT '0.00',
	`tax_amount` decimal(10,2) DEFAULT '0.00',
	`total` decimal(10,2) DEFAULT '0.00',
	`financing_offered` boolean DEFAULT false,
	`monthly_payment` decimal(10,2),
	`financing_term_months` int,
	`valid_until` bigint,
	`accepted_at` bigint,
	`declined_at` bigint,
	`decline_reason` text,
	`notes` text,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_estimates_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_job_reviews` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`technician_id` int,
	`business_id` int NOT NULL,
	`overall_rating` int NOT NULL,
	`technician_rating` int,
	`value_rating` int,
	`quality_rating` int,
	`punctuality_rating` int,
	`review_text` text,
	`routed_to_public` boolean DEFAULT false,
	`routed_to_internal` boolean DEFAULT false,
	`public_platform` varchar(50),
	`public_review_url` varchar(512),
	`business_response` text,
	`responded_at` bigint,
	`created_at` bigint NOT NULL,
	CONSTRAINT `fsm_job_reviews_id` PRIMARY KEY(`id`),
	CONSTRAINT `fsm_job_reviews_job_id_unique` UNIQUE(`job_id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_jobs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`technician_id` int,
	`equipment_id` int,
	`job_number` varchar(50) NOT NULL,
	`type` enum('service_call','installation','maintenance','inspection','estimate_only','warranty','emergency','follow_up') NOT NULL DEFAULT 'service_call',
	`status` enum('new_lead','booked','confirmed','dispatched','in_progress','completed','invoiced','paid','cancelled','on_hold') NOT NULL DEFAULT 'new_lead',
	`priority` enum('low','normal','high','emergency') DEFAULT 'normal',
	`title` varchar(300) NOT NULL,
	`description` text,
	`customer_notes` text,
	`internal_notes` text,
	`scheduled_at` bigint,
	`scheduled_end_at` bigint,
	`arrived_at` bigint,
	`completed_at` bigint,
	`estimated_duration_mins` int DEFAULT 60,
	`service_address` text,
	`service_city` varchar(100),
	`service_state` varchar(50),
	`service_zip` varchar(20),
	`estimated_value` decimal(10,2),
	`final_amount` decimal(10,2),
	`stripe_payment_intent_id` varchar(64),
	`ai_job_brief_generated` boolean DEFAULT false,
	`ai_pre_call_completed` boolean DEFAULT false,
	`ai_pre_call_summary` text,
	`ai_risk_flags` json,
	`source` enum('phone','online_booking','ai_agent','walk_in','referral','repeat','campaign') DEFAULT 'phone',
	`referral_job_id` int,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_jobs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_pre_calls` (
	`id` int AUTO_INCREMENT NOT NULL,
	`job_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`status` enum('scheduled','in_progress','completed','failed','no_answer','skipped') DEFAULT 'scheduled',
	`scheduled_at` bigint,
	`started_at` bigint,
	`completed_at` bigint,
	`duration_seconds` int,
	`call_sid` varchar(100),
	`recording_url` varchar(512),
	`transcript` text,
	`ai_summary` text,
	`symptoms_captured` json,
	`photos_requested_via_sms` boolean DEFAULT false,
	`appointment_confirmed` boolean DEFAULT false,
	`customer_concerns` text,
	`parts_to_pre_stage` json,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_pre_calls_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_pricebook` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`category` varchar(100) NOT NULL,
	`name` varchar(300) NOT NULL,
	`description` text,
	`type` enum('labor','part','material','service_package') DEFAULT 'labor',
	`base_price` decimal(10,2) NOT NULL,
	`member_price` decimal(10,2),
	`emergency_multiplier` decimal(4,2) DEFAULT '1.50',
	`market_price_low` decimal(10,2),
	`market_price_high` decimal(10,2),
	`market_price_avg` decimal(10,2),
	`last_benchmarked_at` bigint,
	`part_number` varchar(100),
	`is_active` boolean DEFAULT true,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_pricebook_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_referrals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source_job_id` int NOT NULL,
	`source_technician_id` int NOT NULL,
	`source_business_id` int NOT NULL,
	`customer_id` int NOT NULL,
	`referred_industry` varchar(100) NOT NULL,
	`referral_description` text NOT NULL,
	`urgency` enum('urgent','soon','when_convenient') DEFAULT 'when_convenient',
	`referred_business_id` int,
	`referred_job_id` int,
	`commission_amount` decimal(10,2),
	`commission_paid` boolean DEFAULT false,
	`commission_paid_at` bigint,
	`status` enum('identified','sent_to_customer','accepted','job_created','completed','declined') DEFAULT 'identified',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_referrals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `fsm_technicians` (
	`id` int AUTO_INCREMENT NOT NULL,
	`business_id` int NOT NULL,
	`user_id` int,
	`name` varchar(200) NOT NULL,
	`email` varchar(320),
	`phone` varchar(30),
	`avatar_url` varchar(512),
	`specialties` json,
	`certifications` json,
	`license_number` varchar(100),
	`years_experience` int DEFAULT 0,
	`status` enum('active','inactive','on_leave') DEFAULT 'active',
	`total_jobs_completed` int DEFAULT 0,
	`average_ticket_size` decimal(10,2) DEFAULT '0.00',
	`average_rating` decimal(3,2) DEFAULT '0.00',
	`conversion_rate` decimal(5,2) DEFAULT '0.00',
	`callback_rate` decimal(5,2) DEFAULT '0.00',
	`upsell_rate` decimal(5,2) DEFAULT '0.00',
	`on_time_rate` decimal(5,2) DEFAULT '100.00',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `fsm_technicians_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoice_line_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`invoice_id` int NOT NULL,
	`description` varchar(500) NOT NULL,
	`quantity` decimal(10,2) DEFAULT '1.00',
	`unit_price` decimal(15,2) NOT NULL,
	`amount` decimal(15,2) NOT NULL,
	`account_id` int,
	`taxable` boolean DEFAULT true,
	`created_at` bigint NOT NULL,
	CONSTRAINT `invoice_line_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `invoices` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`invoice_number` varchar(50) NOT NULL,
	`client_id` int,
	`client_name` varchar(200),
	`client_email` varchar(320),
	`client_address` text,
	`issue_date` bigint NOT NULL,
	`due_date` bigint NOT NULL,
	`status` enum('draft','sent','viewed','partial','paid','overdue','voided') DEFAULT 'draft',
	`subtotal` decimal(15,2) DEFAULT '0.00',
	`tax_rate` decimal(5,2) DEFAULT '0.00',
	`tax_amount` decimal(15,2) DEFAULT '0.00',
	`discount_amount` decimal(15,2) DEFAULT '0.00',
	`total` decimal(15,2) DEFAULT '0.00',
	`amount_paid` decimal(15,2) DEFAULT '0.00',
	`currency` varchar(10) DEFAULT 'USD',
	`notes` text,
	`terms` text,
	`stripe_payment_link` varchar(500),
	`paid_at` bigint,
	`sent_at` bigint,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `invoices_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `journal_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`entry_number` varchar(30),
	`date` bigint NOT NULL,
	`description` text,
	`reference` varchar(100),
	`status` enum('draft','posted','voided') DEFAULT 'draft',
	`total_debit` decimal(15,2) DEFAULT '0.00',
	`total_credit` decimal(15,2) DEFAULT '0.00',
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `journal_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `journal_entry_lines` (
	`id` int AUTO_INCREMENT NOT NULL,
	`journal_entry_id` int NOT NULL,
	`account_id` int NOT NULL,
	`description` text,
	`debit` decimal(15,2) DEFAULT '0.00',
	`credit` decimal(15,2) DEFAULT '0.00',
	`created_at` bigint NOT NULL,
	CONSTRAINT `journal_entry_lines_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vendors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`name` varchar(200) NOT NULL,
	`email` varchar(320),
	`phone` varchar(30),
	`address` text,
	`tax_id` varchar(50),
	`payment_terms` varchar(100),
	`notes` text,
	`created_at` bigint NOT NULL,
	`updated_at` bigint NOT NULL,
	CONSTRAINT `vendors_id` PRIMARY KEY(`id`)
);
