CREATE TABLE `business_brain_change_sets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brainId` int NOT NULL,
	`userId` int NOT NULL,
	`trigger` varchar(128) NOT NULL,
	`affectedTargets` json,
	`proposedChanges` json,
	`status` enum('DRAFT','APPLIED','DISCARDED') NOT NULL DEFAULT 'DRAFT',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`appliedAt` timestamp,
	CONSTRAINT `business_brain_change_sets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `business_brain_faqs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brainId` int NOT NULL,
	`userId` int NOT NULL,
	`question` text NOT NULL,
	`answer` longtext NOT NULL,
	`source` enum('WEBSITE','OWNER','VERTICAL_TEMPLATE') NOT NULL DEFAULT 'WEBSITE',
	`isApproved` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_brain_faqs_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `business_brain_locations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brainId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(160) NOT NULL,
	`address` text,
	`city` varchar(128),
	`state` varchar(64),
	`country` varchar(64) DEFAULT 'US',
	`postalCode` varchar(32),
	`serviceAreaMiles` int,
	`parkingInstructions` text,
	`accessInstructions` text,
	`calendarConfig` json,
	`hoursOverride` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_brain_locations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `business_brain_people` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brainId` int NOT NULL,
	`locationId` int,
	`userId` int NOT NULL,
	`name` varchar(160) NOT NULL,
	`role` varchar(128),
	`department` varchar(128),
	`phone` varchar(64),
	`email` varchar(320),
	`languages` json,
	`skills` json,
	`certifications` json,
	`serviceArea` varchar(255),
	`availability` json,
	`calendarConfig` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_brain_people_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `business_brain_services` (
	`id` int AUTO_INCREMENT NOT NULL,
	`brainId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`price` decimal(12,2),
	`priceRange` varchar(128),
	`durationMinutes` int,
	`deposit` decimal(12,2),
	`taxRule` varchar(128),
	`appointmentType` varchar(160),
	`preparationRequirements` text,
	`cancellationRules` text,
	`upsells` json,
	`crossSells` json,
	`locationIds` json,
	`peopleIds` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_brain_services_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `business_brains` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`verticalPackId` int,
	`prospectId` int,
	`websiteSiteId` int,
	`serviceBusinessId` int,
	`status` enum('DRAFT','REVIEW_READY','ACTIVE','ARCHIVED') NOT NULL DEFAULT 'DRAFT',
	`businessName` varchar(255) NOT NULL,
	`dbaName` varchar(255),
	`legalName` varchar(255),
	`websiteUrl` varchar(1024),
	`industry` varchar(160),
	`subIndustry` varchar(160),
	`yearsInBusiness` int,
	`logoUrl` varchar(1024),
	`businessDescription` longtext,
	`tagline` varchar(255),
	`brandPersonality` varchar(64) NOT NULL DEFAULT 'professional',
	`primaryPhone` varchar(64),
	`smsPhone` varchar(64),
	`primaryEmail` varchar(320),
	`salesEmail` varchar(320),
	`supportEmail` varchar(320),
	`emergencyPhone` varchar(64),
	`hours` json,
	`afterHoursRules` longtext,
	`policies` json,
	`paymentRules` json,
	`escalationRules` json,
	`socialLinks` json,
	`sourceFacts` json,
	`confirmedFields` json,
	`generatedPrompt` longtext,
	`generatedAt` timestamp,
	`reviewedAt` timestamp,
	`activatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `business_brains_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vertical_prompt_packs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(160) NOT NULL,
	`category` varchar(96) NOT NULL,
	`description` text,
	`basePrompt` longtext NOT NULL,
	`safetyRules` json,
	`qualificationFields` json,
	`suggestedServices` json,
	`suggestedCrmFields` json,
	`recommendedChannels` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `vertical_prompt_packs_id` PRIMARY KEY(`id`),
	CONSTRAINT `vertical_prompt_packs_slug_unique` UNIQUE(`slug`)
);
