import { FormEvent, useState } from "react";
import { useRoute } from "wouter";
import { ArrowUp, Bot, ExternalLink, LockKeyhole } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Message = { role: "assistant" | "user"; content: string };

export default function ProspectPresentationPage() {
  const [, params] = useRoute("/prospect-presentation/:slug");
  const slug = params?.slug ?? "";
  const presentation = trpc.prospecting.getPublicPresentation.useQuery({ presentationSlug: slug }, { enabled: !!slug });
  const [messages, setMessages] = useState<Message[]>([{ role: "assistant", content: "Welcome. I can walk you through this private VonWork website concept and the optional upgrades that may fit your business." }]);
  const [draft, setDraft] = useState("");
  const ask = trpc.prospecting.askPresentation.useMutation({ onSuccess: (result) => setMessages((current) => [...current, { role: "assistant", content: result.message }]) });
  const submit = (event: FormEvent) => { event.preventDefault(); const message = draft.trim(); if (!message || ask.isPending) return; setMessages((current) => [...current, { role: "user", content: message }]); setDraft(""); ask.mutate({ presentationSlug: slug, message }); };
  if (presentation.isLoading) return <div className="min-h-screen grid place-items-center text-gray-500">Preparing private presentation…</div>;
  if (!presentation.data) return <div className="min-h-screen grid place-items-center p-6 text-center"><div><LockKeyhole className="w-10 h-10 text-gray-400 mx-auto mb-3"/><h1 className="font-extrabold text-xl text-gray-900">This private presentation is unavailable</h1><p className="text-gray-500 mt-2">It may have expired or not yet been approved for sharing.</p></div></div>;
  return <main className="min-h-screen bg-[#f5f7fa] text-gray-900"><header className="bg-gradient-to-r from-[#1A6FFF] to-[#0052CC] text-white px-6 py-5"><div className="max-w-5xl mx-auto flex items-center gap-3"><Bot className="w-6 h-6"/><div><p className="font-extrabold">VonWork AI Presenter</p><p className="text-sm text-blue-100">Private concept for {presentation.data.title}</p></div></div></header><div className="max-w-5xl mx-auto p-6 grid lg:grid-cols-[1fr_360px] gap-6"><section className="bg-white border border-gray-200 rounded-2xl p-6"><p className="text-xs font-extrabold tracking-widest text-blue-600 uppercase">Private concept walkthrough</p><h1 className="text-3xl font-extrabold mt-2">A clearer digital front door for your business</h1><p className="text-gray-600 mt-3">This is a private concept presentation, not a live website and not a guarantee of outcomes. Review the design first, then ask the AI presenter what may be useful for your goals.</p><a href={`/prospect-demo/${presentation.data.demoSlug}`} target="_blank" rel="noreferrer" className="inline-flex mt-5 bg-[#1A6FFF] hover:bg-[#0052CC] text-white font-bold px-4 py-3 rounded-xl">Open website concept <ExternalLink className="w-4 h-4 ml-2" /></a><div className="mt-8 rounded-xl bg-blue-50 border border-blue-100 p-4"><p className="font-bold text-blue-950">Presentation outline</p><p className="text-sm text-blue-900 mt-2 whitespace-pre-wrap">{presentation.data.script}</p></div></section><aside className="bg-white border border-gray-200 rounded-2xl overflow-hidden flex flex-col min-h-[520px]"><div className="p-4 border-b border-gray-100"><p className="font-extrabold">Ask the AI presenter</p><p className="text-xs text-gray-500 mt-1">Text presentation only. AI voice/video is available only with documented consent and a booked meeting.</p></div><div className="p-4 flex-1 space-y-3 overflow-auto">{messages.map((message, index) => <div key={index} className={`rounded-xl p-3 text-sm ${message.role === "assistant" ? "bg-blue-50 text-blue-950" : "bg-gray-100 text-gray-800 ml-6"}`}>{message.content}</div>)}{ask.isPending ? <div className="text-xs text-gray-500">Presenter is preparing a response…</div> : null}</div><form onSubmit={submit} className="p-3 border-t border-gray-100 flex gap-2"><Input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Ask about the design, AI chat, SEO, or booking…" /><Button type="submit" size="icon" disabled={!draft.trim() || ask.isPending} className="bg-[#1A6FFF]"><ArrowUp className="w-4 h-4" /></Button></form></aside></div></main>;
}
